# Generated by Django 5.0.2 on 2024-06-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_oreder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='oreder_status',
            new_name='orederstatus',
        ),
    ]
