# Generated by Django 5.0.2 on 2024-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_oreder_status_cart_orederstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='pddress',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='place',
            field=models.CharField(default=0),
        ),
    ]
