# Generated by Django 5.0.2 on 2024-07-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_city_cart_email_cart_name_cart_pddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pddress',
            new_name='address',
        ),
    ]
