# Generated by Django 5.0.2 on 2024-07-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_pddress_cart_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='place',
            field=models.CharField(),
        ),
    ]
