# Generated by Django 5.0.2 on 2024-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_address_alter_cart_city_alter_cart_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
